# Generated by Django 3.2.6 on 2021-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
