# Generated by Django 3.2.6 on 2021-09-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=45, verbose_name='Имя')),
                ('point_A', models.CharField(max_length=45, verbose_name='Имя')),
                ('point_B', models.CharField(max_length=45, verbose_name='Имя')),
                ('thing', models.CharField(max_length=45, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=45, verbose_name='Имя')),
                ('name', models.CharField(max_length=45, verbose_name='Имя')),
                ('time_to_call', models.CharField(max_length=45, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Заявка ',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
