# Generated by Django 3.2.6 on 2021-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_road'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя:')),
                ('email', models.CharField(max_length=45, verbose_name='E-mail:')),
                ('text', models.TextField(verbose_name='Текс сообщения:')),
            ],
            options={
                'verbose_name': 'Письма-Email ',
                'verbose_name_plural': 'Письма-Email',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Отызыв клиента ', 'verbose_name_plural': 'Отзывы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='client_road',
            options={'verbose_name': 'Заявка с описанием ', 'verbose_name_plural': 'Заявки с описанием'},
        ),
        migrations.AlterField(
            model_name='client_road',
            name='date',
            field=models.CharField(max_length=45, verbose_name='Дата:'),
        ),
        migrations.AlterField(
            model_name='client_road',
            name='point_A',
            field=models.CharField(max_length=45, verbose_name='Откуда:'),
        ),
        migrations.AlterField(
            model_name='client_road',
            name='point_B',
            field=models.CharField(max_length=45, verbose_name='Куда:'),
        ),
        migrations.AlterField(
            model_name='client_road',
            name='telephone',
            field=models.CharField(max_length=45, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='client_road',
            name='thing',
            field=models.CharField(max_length=45, verbose_name='Что перевозим:'),
        ),
        migrations.AlterField(
            model_name='client_road',
            name='time_to_call',
            field=models.CharField(max_length=45, verbose_name='Перезвонить:'),
        ),
    ]
